version: '3.8'

services:
  privatestream:
    build: .
    container_name: privatestream_nas
    restart: unless-stopped
    ports:
      - "3000:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data # Map where the sqlite db is stored if you change DB_PATH to /app/data/privatestream.db
    environment:
      - NODE_ENV=production
      - PORT=3001
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"